---
:values:
:filter:
  :azure_client_id: azure_client_id
  :azure_client_key: azure_client_key
  :azure_tenant_id: azure_tenant_id
  :azure_storage_account1: my-azure-storage-account1
  :azure_storage_account2: my-azure-storage-account2
  :azure_storage_account3: my-azure-storage-account3
  :azure_storage_account4: my-azure-storage-account4
  :azure_storage_account5: my-azure-storage-account5
:default:
