# Middleware Server daily performance chart layouts
---
- :title: JVM Heap Usage (Bytes)
  :type: Line
  :columns:
  - mw_heap_used
  - mw_heap_committed
  - mw_heap_max

- :title: JVM Non Heap Usage (Bytes)
  :type: Line
  :columns:
  - mw_non_heap_used
  - mw_non_heap_committed

- :title: GC Duration (ms)
  :type: Line
  :columns:
  - mw_accumulated_gc_duration

- :title: Web Sessions
  :type: Line
  :columns:
  - mw_aggregated_active_web_sessions
  - mw_aggregated_expired_web_sessions
  - mw_aggregated_rejected_web_sessions

- :title: Transactions
  :type: Line
  :columns:
  - mw_tx_committed
  - mw_tx_timeout
  - mw_tx_heuristics
  - mw_tx_application_rollbacks
  - mw_tx_aborted
  - mw_tx_resource_rollbacks
