# VmdbDatabase Daily performance chart layouts
--- 
- :title: Disk Size
  :type: Line
  :columns:
  - disk_total_bytes
  - disk_free_bytes
  - disk_used_bytes
  :menu: 
  :decimals: 2
  :units: GB

- :title: Index Nodes
  :type: Line
  :columns:
  - disk_total_inodes
  - disk_free_inodes
  - disk_used_inodes
  :menu: 
