# Middleware Messaging realtime performance chart layouts
---
- :title: Messages
  :type: Line
  :columns:
  - mw_ms_topic_delivering_count
  - mw_ms_topic_durable_message_count
  - mw_ms_topic_message_count
  - mw_ms_topic_message_added
  - mw_ms_topic_non_durable_message_count

- :title: Subscribers
  :type: Line
  :columns:
  - mw_ms_topic_durable_subscription_count
  - mw_ms_topic_non_durable_subscription_count
  - mw_ms_topic_subscription_count