# Middleware Datasource real time performance chart layouts
---
- :title: Availability (Connections)
  :type: Line
  :columns:
  - mw_ds_available_count
  - mw_ds_in_use_count
  - mw_ds_timed_out

- :title: Responsiveness (ms)
  :type: Line
  :columns:
  - mw_ds_average_get_time
  - mw_ds_average_creation_time
  - mw_ds_max_wait_time