#
# This is an MIQ Report configuration file
#   Single value parameters are specified as:
#     single_value_parm: value
#   Multiple value parameters are specified as:
#     multi_value_parm:
#       - value 1
#       - value 2
#

# Report title
title: "VIM Performance Daily"

# Menu name
name: "VIM Performance Daily"

rpt_type: middleware

# Main DB table report is based on
db: LiveMetric

# Columns to fetch from the main table
cols:
- timestamp
- mw_ms_topic_delivering_count
- mw_ms_topic_durable_message_count
- mw_ms_topic_durable_suscription_count
- mw_ms_topic_message_count
- mw_ms_topic_message_added
- mw_ms_topic_non_durable_message_count
- mw_ms_topic_non_durable_suscription_count
- mw_ms_topic_suscription_count

# Included tables (joined, has_one, has_many) and columns
include:

# Order of columns (from all tables)
col_order:
- timestamp
- mw_ms_topic_delivering_count
- mw_ms_topic_durable_message_count
- mw_ms_topic_durable_suscription_count
- mw_ms_topic_message_count
- mw_ms_topic_message_added
- mw_ms_topic_non_durable_message_count
- mw_ms_topic_non_durable_suscription_count
- mw_ms_topic_suscription_count

# Column titles, in order
headers:
- Date/Time
- Delivering Message Count
- Durable Message Count
- Durable Subscription Count
- Messages Count
- Messages Added
- Non Durable Messages Dount
- Non Durable Subscription Count
- Subscription Count

# Condition expression for search filtering
conditions:

# Order string for the SQL query
order: ascending

# Columns to sort the report on, in order
sortby: timestamp

# Group rows (y=yes,n=no,c=count)
group: n

# Graph type
#   Bar
#   Column
#   ColumnThreed
#   ParallelThreedColumn
#   Pie
#   PieThreed
#   StackedBar
#   StackedColumn
#   StackedThreedColumn

graph:
  :type: Line
  :columns:
    - mw_ms_topic_delivering_count
    - mw_ms_topic_durable_message_count
    - mw_ms_topic_durable_suscription_count
    - mw_ms_topic_message_count
    - mw_ms_topic_message_added
    - mw_ms_topic_non_durable_message_count
    - mw_ms_topic_non_durable_suscription_count
    - mw_ms_topic_suscription_count
# Dimensions of graph (1 or 2)
#   Note: specifying 2 for a single dimension graph may not return expected results
dims:

template_type: report
