#
# This is an MIQ Report configuration file
#   Single value parameters are specified as:
#     single_value_parm: value
#   Multiple value parameters are specified as:
#     multi_value_parm:
#       - value 1
#       - value 2
#

# Report title
title: "VIM Utilization Daily"

# Menu name
name: "VIM Utilization Daily"

# Main DB table report is based on
db: VimPerformanceDaily

# Columns to fetch from the main table
cols:
- timestamp
- max_derived_cpu_available
- max_derived_cpu_reserved
- max_cpu_usagemhz_rate_average
- cpu_usagemhz_rate_average
- trend_max_cpu_usagemhz_rate_average
- trend_cpu_usagemhz_rate_average
- max_derived_memory_available
- max_derived_memory_reserved
- max_derived_memory_used
- derived_memory_used
- trend_max_derived_memory_used
- trend_derived_memory_used
- derived_storage_total
- max_v_derived_storage_used
- v_derived_storage_used
- trend_max_v_derived_storage_used
- trend_v_derived_storage_used
# Do not remove the following line - derived_storage_free needs to be included to enable calculation of virtual col: v_derived_storage_used
- derived_storage_free
#- max_disk_usage_rate_average
#- trend_max_disk_usage_rate_average
#- max_net_usage_rate_average
#- trend_max_net_usage_rate_average

# Included tables (joined, has_one, has_many) and columns
include:

# Order of columns (from all tables)
col_order:
- timestamp
- max_derived_cpu_available
- max_derived_cpu_reserved
- max_cpu_usagemhz_rate_average
- cpu_usagemhz_rate_average
- trend_max_cpu_usagemhz_rate_average
- trend_cpu_usagemhz_rate_average
- max_derived_memory_available
- max_derived_memory_reserved
- max_derived_memory_used
- derived_memory_used
- trend_max_derived_memory_used
- trend_derived_memory_used
- derived_storage_total
- max_v_derived_storage_used
- v_derived_storage_used
- trend_max_v_derived_storage_used
- trend_v_derived_storage_used
#- max_disk_usage_rate_average
#- trend_max_disk_usage_rate_average
#- max_net_usage_rate_average
#- trend_max_net_usage_rate_average

# Column titles, in order
headers:
- Date/Time
- Max Total
- Max Available
- Max Used
- Avg Used
- Trend Max Used
- Trend Avg Used
- Max Total
- Max Available
- Max Used
- Avg Used
- Trend Max Used
- Trend Avg Used
- Max Total
- Max Used
- Avg Used
- Trend Max Used
- Trend Avg Used
#- Max I/O
#- Trend Max I/O
#- Max I/O
#- Trend Max I/O

# Condition expression for search filtering
conditions:

# Order string for the SQL query
order: ascending

# Columns to sort the report on, in order
sortby: timestamp

# Group rows (y=yes,n=no,c=count)
group: n

# Graph type
#   Bar
#   Column
#   ColumnThreed
#   ParallelThreedColumn
#   Pie
#   PieThreed
#   StackedBar
#   StackedColumn
#   StackedThreedColumn

graph:
  :type: Line
  :columns:
  - cpu_usage_rate_average

# Dimensions of graph (1 or 2)
#   Note: specifying 2 for a single dimension graph may not return expected results
dims:

template_type: report
