#
# Toolbar config file
#
---
:model: ManageIQ::Providers::Foreman::ConfigurationManager::ConfiguredSystem
:button_groups:
- :name: provider_foreman_lifecycle
  :items:
  - :buttonSelect: provider_foreman_lifecycle_choice
    :image: lifecycle
    :title: Lifecycle
    :text: Lifecycle
    :enabled: 'true'
    :items:
    - :button: provider_foreman_configured_system_provision
      :image: new
      :text: "Provision Configured Systems"
      :title: "Provision Configured Systems"
      :url: provision
      :url_parms: 'main_div'
      :enabled: 'false'
      :onwhen: '1+'
- :name: provider_foreman_policy
  :items:
  - :buttonSelect: provider_foreman_policy_choice
    :image: policy
    :title: Policy
    :text: Policy
    :items:
    - :button: provider_foreman_configured_system_tag
      :image: tag
      :text: "Edit Tags"
      :title: "Edit Tags for this Configured System"
      :url: tagging
      :url_parms: 'main_div'
      :enabled: 'false'
      :onwhen: '1+'
