#
# Toolbar config file
#
---
:model: ConfigurationProfile
:button_groups:
- :name: provider_vmdb
  :items:
  - :buttonSelect: provider_vmdb_choice
    :icon: fa fa-cog fa-lg
    :title: Configuration
    :text: Configuration
    :enabled: 'true'
    :items:
    - :button: provider_foreman_refresh
      :icon: fa fa-refresh fa-lg
      :text: "Refresh Relationships and Power states"
      :title: "Refresh relationships for all items related to this Provider"
      :url: refresh
      :confirm: "Refresh relationships for all items related to this Provider?"
    - :separator:
    - :button: provider_foreman_edit
      :icon: pficon pficon-edit fa-lg
      :text: Edit this Provider
      :title: Edit this Provider
      :url: edit
    - :button: provider_foreman_delete
      :icon: pficon pficon-delete fa-lg
      :text: Remove this Provider from the VMDB
      :title: Remove this Provider from the VMDB
      :url: delete
      :confirm: "Warning: The selected Provider and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Provider?"
