#
# This is an MIQ Report configuration file
#   Single value parameters are specified as:
#     single_value_parm: value
#   Multiple value parameters are specified as:
#     multi_value_parm:
#       - value 1
#       - value 2
#

# Report title
title: Repository

# Menu name
name: Repository

# Main DB table report is based on
db: ConfigurationScriptSource

# Columns to fetch from the main table
cols:
- name
- description
- total_payloads
- created_at
- updated_at

# Included tables (joined, has_one, has_many) and columns

# Included tables and columns for query performance

# Order of columns (from all tables)
col_order:
- name
- description
- total_payloads
- created_at
- updated_at

# Column titles, in order
headers:
- Name
- Description
- Playbooks
- Created On
- Updated On

col_formats:
-
-
-
-

# Condition(s) string for the SQL query
conditions:

# Order string for the SQL query
order: Ascending

# Columns to sort the report on, in order
sortby:
- name

# Group rows (y=yes,n=no,c=count)
group: n

# Graph type
#   Bar
#   Column
#   ColumnThreed
#   ParallelThreedColumn
#   Pie
#   PieThreed
#   StackedBar
#   StackedColumn
#   StackedThreedColumn

graph:

# Dimensions of graph (1 or 2)
#   Note: specifying 2 for a single dimension graph may not return expected results
dims:
