#
# This is an MIQ Report configuration file
#   Single value parameters are specified as:
#     single_value_parm: value
#   Multiple value parameters are specified as:
#     multi_value_parm:
#       - value 1
#       - value 2
#

# Report title
title: Ansible Tower Providers

# Menu name
name: ConfigurationManagerForeman

# Main DB table report is based on
db: ManageIQ::Providers::AnsibleTower::AutomationManager

# Columns to fetch from the main table
cols:
- name
- url
- type
- zone.name
- last_refresh_date
- region_description
- authentication_status
- total_configured_systems

# Included tables (joined, has_one, has_many) and columns
include:
  zone:
    columns:
    - name
  provider:
    columns:
    - name
    - url

# Included tables and columns for query performance
include_for_find:
  :zone: {}
  :provider: {}

# Order of columns (from all tables)
col_order:
- name
- provider.url
- type
- zone.name
- last_refresh_date
- region_description
- authentication_status
- total_configured_systems

# Column titles, in order
headers:
- Provider Name
- URL
- Type
- Zone
- Last Refresh Date
- Region Description
- Status
- Total Configured Systems

col_formats:
-
-
- :model_name
-
-

# Condition(s) string for the SQL query
conditions:

# Order string for the SQL query
order: Ascending

# Columns to sort the report on, in order
sortby:
- name

# Group rows (y=yes,n=no,c=count)
group: n

# Graph type
#   Bar
#   Column
#   ColumnThreed
#   ParallelThreedColumn
#   Pie
#   PieThreed
#   StackedBar
#   StackedColumn
#   StackedThreedColumn

graph:

# Dimensions of graph (1 or 2)
#   Note: specifying 2 for a single dimension graph may not return expected results
dims:
