#
# This is an MIQ Report configuration file
#   Single value parameters are specified as:
#     single_value_parm: value
#   Multiple value parameters are specified as:
#     multi_value_parm:
#       - value 1
#       - value 2
#

# Report title
title: Middleware Deployments

# Menu name
name: Middleware Deployments

# Main DB table report is based on
db: MiddlewareDeployment

# Columns to fetch from the main table
cols:
- name
- status

# Order of columns (from all tables)
col_order:
- name
- status
- middleware_server.name
- middleware_server.hostname

# Column titles, in order
headers:
- Deployment Name
- Status
- Server
- Host Name

# Condition(s) string for the SQL query
conditions:

# Order string for the SQL query
order: Ascending

# Columns to sort the report on, in order
sortby:
- name
- middleware_server.name
- middleware_server.hostname

# Group rows (y=yes,n=no,c=count)
group: y


# Graph type
#   Bar
#   Column
#   ColumnThreed
#   ParallelThreedColumn
#   Pie
#   PieThreed
#   StackedBar
#   StackedColumn
#   StackedThreedColumn

graph:

# Dimensions of graph (1 or 2)
#   Note: specifying 2 for a single dimension graph may not return expected results
dims:
