# Container node daily performance chart layouts
---
- :title: CPU (%)
  :type: Line
  :columns:
  - cpu_usage_rate_average

- :title: Memory (MB)
  :type: Line
  :columns:
  - derived_memory_used
  - derived_memory_available

- :title: Network I/O (KBps)
  :type: Line
  :columns:
  - net_usage_rate_average
