# Middleware Messaging daily performance chart layouts
---
- :title: Messages
  :type: Line
  :columns:
  - mw_ms_queue_delivering_count
  - mw_ms_queue_message_count
  - mw_ms_queue_messages_added

- :title: Consumers
  :type: Line
  :columns:
  - mw_ms_queue_consumer_count