---
http_interactions:
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Thu, 22 Dec 2016 07:42:19 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=eba450abe5a9ff4df0d24483d1024dfa; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Thu, 22 Dec 2016 07:42:19 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/counters/machine%2Fcapture.context.com%2Fcpu%2Fusage/stats/?bucketDuration=20s&start=1482306053000
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json
      Date:
      - Thu, 22 Dec 2016 07:42:20 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=eba450abe5a9ff4df0d24483d1024dfa; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '[{"start":1482306053000,"end":1482306073000,"min":1.54760358235403E14,"avg":1.54761471914033E14,"median":1.54760358235403E14,"max":1.54762585592663E14,"sum":3.09522943828066E14,"samples":2,"empty":false},{"start":1482392533000,"end":1482392553000,"empty":true}]'
    http_version: 
  recorded_at: Thu, 22 Dec 2016 07:42:20 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Thu, 22 Dec 2016 07:42:20 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=eba450abe5a9ff4df0d24483d1024dfa; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Thu, 22 Dec 2016 07:42:20 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/gauges/machine%2Fcapture.context.com%2Fmemory%2Fusage/stats/?bucketDuration=20s&start=1482306073000
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json
      Date:
      - Thu, 22 Dec 2016 07:42:22 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=eba450abe5a9ff4df0d24483d1024dfa; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '[{"start":1482306073000,"end":1482306093000,"min":3.469869056E9,"avg":3.469901824E9,"median":3.469869056E9,"max":3.469934592E9,"sum":6.939803648E9,"samples":2,"empty":false},{"start":1482392533000,"end":1482392553000,"empty":true}]'
    http_version: 
  recorded_at: Thu, 22 Dec 2016 07:42:22 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Thu, 22 Dec 2016 07:42:22 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=eba450abe5a9ff4df0d24483d1024dfa; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Thu, 22 Dec 2016 07:42:22 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/counters/machine%2Fcapture.context.com%2Fnetwork%2Ftx/stats/?bucketDuration=20s&start=1482306053000
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json
      Date:
      - Thu, 22 Dec 2016 07:42:24 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=eba450abe5a9ff4df0d24483d1024dfa; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '[{"start":1482306053000,"end":1482306073000,"min":1.4290391845E10,"avg":1.42905156885E10,"median":1.4290391845E10,"max":1.4290639532E10,"sum":2.8581031377E10,"samples":2,"empty":false},{"start":1482392533000,"end":1482392553000,"empty":true}]'
    http_version: 
  recorded_at: Thu, 22 Dec 2016 07:42:24 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Thu, 22 Dec 2016 07:42:24 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=eba450abe5a9ff4df0d24483d1024dfa; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Thu, 22 Dec 2016 07:42:24 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/counters/machine%2Fcapture.context.com%2Fnetwork%2Frx/stats/?bucketDuration=20s&start=1482306053000
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json
      Date:
      - Thu, 22 Dec 2016 07:42:25 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=eba450abe5a9ff4df0d24483d1024dfa; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '[{"start":1482306053000,"end":1482306073000,"min":1.3327668735E10,"avg":1.3327726648E10,"median":1.3327668735E10,"max":1.3327784561E10,"sum":2.6655453296E10,"samples":2,"empty":false},{"start":1482392533000,"end":1482392553000,"empty":true}]'
    http_version: 
  recorded_at: Thu, 22 Dec 2016 07:42:25 GMT
recorded_with: VCR 3.0.3
