---
- :aut
- :clo
- :cnt
- :compute
- :con
- :conf
- :inf
- :net
- :opt
- :set
- :sto
- :svc
- :vi
- ems-type:ansible_tower_configuration
- ems-type:atomic
- ems-type:atomic_enterprise
- ems-type:azure
- ems-type:azure_network
- ems-type:ec2
- ems-type:ec2_network
- ems-type:foreman_configuration
- ems-type:foreman_provisioning
- ems-type:gce
- ems-type:hawkular
- ems-type:kubernetes
- ems-type:openshift
- ems-type:openshift_enterprise
- ems-type:openstack
- ems-type:openstack_infra
- ems-type:openstack_network
- ems-type:rhevm
- ems-type:scvmm
- ems-type:vmwarews
