---
- :aut
- :automate
- :clo
- :cnt
- :compute
- :con
- :conf
- :inf
- :mdl
- :dwh
- :net
- :opt
- :set
- :sto
- :svc
- :vi
- ems-type:ansible_tower_automation
- ems-type:azure
- ems-type:azure_network
- ems-type:cinder
- ems-type:ec2
- ems-type:ec2_network
- ems-type:ec2_ebs_storage
- ems-type:embedded_ansible_automation
- ems-type:s3
- ems-type:foreman_configuration
- ems-type:foreman_provisioning
- ems-type:gce
- ems-type:gce_network
- ems-type:hawkular
- ems-type:hawkular_datawarehouse
- ems-type:kubernetes
- ems-type:nuage_network
- ems-type:openshift
- ems-type:openshift_enterprise
- ems-type:openstack
- ems-type:openstack_infra
- ems-type:openstack_network
- ems-type:physical_infra_manager
- ems-type:rhevm
- ems-type:scvmm
- ems-type:swift
- ems-type:vmware_cloud
- ems-type:vmware_cloud_network
- ems-type:vmwarews
