---
- :vi
- :svc
- :clo
- :inf
- :con
- :cnt
- :mdl
- :net
- :aut
- :opt
- :set
- ems-type:foreman_configuration
- ems-type:scvmm
- ems-type:openstack_infra
- ems-type:openstack_network
- ems-type:rhevm
- ems-type:vmwarews
- ems-type:azure
- ems-type:ec2
- ems-type:openstack
- ems-type:kubernetes
- ems-type:openshift
- ems-type:atomic
- ems-type:openshift_enterprise
- ems-type:atomic_enterprise
- ems-type:foreman_provisioning
- ems-type:gce
